---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: benji-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://benji-backup.me/helm-charts/
  timeout: 3m
