---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: pod-arcade-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://charts.pod-arcade.com
  timeout: 3m
