apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - db
  - backup-system
  - default
  - flux-system
  - games
  - home
  - kube-system
  - monitoring
  - networking
  - system-upgrade
