apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mc-forge
  - mc-survival
  - mc-sre
  - mc-22
  - mc-potato-smp
  - mc-potato-creative
  - mc-school
  - mc-curseforge
  - mc-potatov
  - factorio
  - filebrowser
  - code-server
